---
title: "Pillar Negative Colors"
author: "Chase Clark"
date: "January 14, 2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}
library(tidyverse)
devtools::install_github("r-lib/pillar")
library("pillar")

```


```{r}
keep_empty <- function(fun) {
  function(x) {
    ret <- rep_along(x, "")
    update <- which(is.na(x) | x != "")
    ret[update] <- fun(x[update])
    ret
  }
}
```



```{r}

# Set pillar.neg
options("pillar.neg"=FALSE)


# Test
style_neg <- keep_empty(function(x) {
  if (isTRUE(getOption("pillar.neg", TRUE))) {
    
    neg_color<-crayon::make_style(rgb(204,75,75,maxColorValue = 256),colors=16)
    
    neg_color(x)
  } else {
    x
  }
})

w<-style_neg("123")
cat(w)



style_neg <- keep_empty(function(x) {
  if (isTRUE(getOption("pillar.neg", TRUE))) {
    
    neg_color<-crayon::make_style(rgb(204,75,75,maxColorValue = 256),colors=16)
    
    neg_color(x)
  } else {
    x
  }
})

w<-style_neg("123")
cat(w)
```

